In [1]:
import numpy as np 
import pandas as pd 
from sklearn.ensemble import RandomForestClassifier,RandomForestRegressor

In [3]:
points2008 = pd.read_csv('IPL 2008 PT.csv')
points2009 = pd.read_csv('IPL 2009 PT.csv')
points2010 = pd.read_csv('IPL 2010 PT.csv')
points2011 = pd.read_csv('IPL 2011 PT.csv')
points2012 = pd.read_csv('IPL 2012 PT.csv')
points2013 = pd.read_csv('IPL 2013 PT.csv')
points2014 = pd.read_csv('IPL 2014 PT.csv')
points2015 = pd.read_csv('IPL 2015 PT.csv')
points2016 = pd.read_csv('IPL 2016 PT.csv')
points2017 = pd.read_csv('IPL 2017 PT.csv')
points2018 = pd.read_csv('IPL 2018 PT.csv')
points2019 = pd.read_csv('IPL 2019 PT.csv')

In [5]:
points2019

,Team,Pld,Won,Lost,Tied,N/R,Net RR,For,Against,Pts
0,Mumbai Indians MI,14,9,5,0,0,0.421,"2,380/275.1","2,282/277.2",18
1,Chennai Super Kings CSK,14,9,5,0,0,0.131,"2,043/274.1","2,012/274.5",18
2,Delhi Capitals DC,14,9,5,0,0,0.044,"2,207/272.5","2,238/278.1",18
3,Sunrisers Hyderabad SRH,14,6,8,0,0,0.577,"2,288/269.2","2,200/277.5",12
4,Kolkata Knight Riders KKR,14,6,8,0,0,0.028,"2,466/270.4","2,419/266.2",12
5,Kings XI Punjab KXIP,14,6,8,0,0,-0.251,"2,429/276.3","2,503/277",12
6,Rajasthan Royals RR,14,5,8,0,1,-0.449,"2,153/257","2,192/248.2",11
7,Royal Challengers Bangalore RCB,14,5,8,0,1,-0.607,"2,146/258.4","2,266/254.3",11

In [6]:
point=points2008.append([points2009,points2010,points2011,points2012,points2013,points2014,points2015,points2016,points2018,points2017,points2019])

In [7]:
points = point.groupby('Team').mean()

In [9]:
matches = pd.read_csv('matches1234.csv')

In [10]:
match = matches.drop(['city','venue','umpire1','win_by_runs','win_by_wickets','season'],axis=1)

In [11]:
def string_remover(df,list1=[],list2=[],drop=[],exclude=[],include=[]):
    a = df.select_dtypes(include='object')
    for i in a.columns:
        list1=[]
        d=0
        if not i in exclude and i in include:
            list1.append(i)
            for x in a.index:
                try:
                    c = list1.index(a[i].iloc[x:x+1][x])
                    a[i].iloc[x:x+1][x] = c
                except:
                    list1.append(a[i].iloc[x:x+1][x])
                    a[i].iloc[x:x+1][x] = len(list1)-1
            list2.append(list1)
            d+=1
    a.fillna(len(list1))
    d = df.select_dtypes(exclude='object').fillna(0)
    try:
        return pd.concat([d,a],axis=1).fillna(0).drop([drop],axis=1)
    except:
        return pd.concat([d,a],axis=1).fillna(0)

In [12]:
match['win']=None
match['toss_win']=None
for i in match.index:
    if match.winner[i] == match.team1[i]:
        match['win'][i] = 'team 1'
    else:
        match['win'][i] = 'team 2'    
    if match.toss_winner[i] == match.team1[i]:
        match['toss_win'][i] = 'team 1'
    else:
        match['toss_win'][i] = 'team 2'

In [13]:
a=[]

In [14]:
b=['toss_decision', 'field', 'bat', 'toss_win', 'team 1', 'team 2']

In [15]:
match

,team1,team2,toss_winner,toss_decision,winner,win,toss_win
0,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,team 1,team 2
1,Mumbai Indians,Rising Pune Supergiants,Rising Pune Supergiants,field,Rising Pune Supergiants,team 2,team 2
2,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders,team 2,team 2
3,Rising Pune Supergiants,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,team 2,team 2
4,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,team 1,team 1
5,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,team 2,team 2
6,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,team 2,team 2
7,Royal Challengers Bangalore,Kings XI Punjab,Royal Challengers Bangalore,bat,Kings XI Punjab,team 2,team 1
8,Delhi Daredevils,Rising Pune Supergiants,Rising Pune Supergiants,field,Delhi Daredevils,team 1,team 2
9,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,team 2,team 2
10,Kings XI Punjab,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders,team 2,team 2
11,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,team 2,team 2
12,Rising Pune Supergiants,Gujarat Lions,Gujarat Lions,field,Gujarat Lions,team 2,team 2
13,Kolkata Knight Riders,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Kolkata Knight Riders,team 1,team 2
14,Delhi Daredevils,Kings XI Punjab,Delhi Daredevils,bat,Delhi Daredevils,team 1,team 1
15,Gujarat Lions,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,team 2,team 2
16,Rising Pune Supergiants,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Rising Pune Supergiants,team 1,team 2
17,Delhi Daredevils,Kolkata Knight Riders,Delhi Daredevils,bat,Kolkata Knight Riders,team 2,team 1
18,Sunrisers Hyderabad,Kings XI Punjab,Kings XI Punjab,field,Sunrisers Hyderabad,team 1,team 2
19,Royal Challengers Bangalore,Gujarat Lions,Gujarat Lions,field,Royal Challengers Bangalore,team 1,team 2
20,Sunrisers Hyderabad,Delhi Daredevils,Sunrisers Hyderabad,bat,Sunrisers Hyderabad,team 1,team 1
21,Kings XI Punjab,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,team 2,team 2
22,Kolkata Knight Riders,Gujarat Lions,Gujarat Lions,field,Gujarat Lions,team 2,team 2
23,Mumbai Indians,Delhi Daredevils,Delhi Daredevils,field,Mumbai Indians,team 1,team 2
24,Sunrisers Hyderabad,Rising Pune Supergiants,Rising Pune Supergiants,field,Rising Pune Supergiants,team 2,team 2
25,Kings XI Punjab,Gujarat Lions,Gujarat Lions,field,Kings XI Punjab,team 1,team 2
26,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Kolkata Knight Riders,team 1,team 2
27,Rising Pune Supergiants,Mumbai Indians,Mumbai Indians,field,Rising Pune Supergiants,team 1,team 2
28,Rising Pune Supergiants,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders,team 2,team 2
29,Royal Challengers Bangalore,Gujarat Lions,Gujarat Lions,field,Gujarat Lions,team 2,team 2
...,...,...,...,...,...,...,...
606,Gujarat Lions,Delhi Daredevils,Delhi Daredevils,field,Delhi Daredevils,team 2,team 2
607,Kolkata Knight Riders,Kings XI Punjab,Kings XI Punjab,field,Kolkata Knight Riders,team 1,team 2
608,Delhi Daredevils,Rising Pune Supergiants,Rising Pune Supergiants,field,Rising Pune Supergiants,team 2,team 2
609,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,team 2,team 2
610,Rising Pune Supergiants,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Royal Challengers Bangalore,team 2,team 2
611,Kings XI Punjab,Delhi Daredevils,Delhi Daredevils,field,Kings XI Punjab,team 1,team 2
612,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,Sunrisers Hyderabad,team 1,team 2
613,Kolkata Knight Riders,Gujarat Lions,Gujarat Lions,field,Gujarat Lions,team 2,team 2
614,Royal Challengers Bangalore,Kings XI Punjab,Kings XI Punjab,field,Royal Challengers Bangalore,team 1,team 2
615,Sunrisers Hyderabad,Rising Pune Supergiants,Sunrisers Hyderabad,bat,Sunrisers Hyderabad,team 1,team 1
616,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,team 2,team 2
617,Sunrisers Hyderabad,Delhi Daredevils,Delhi Daredevils,field,Delhi Daredevils,team 2,team 2
618,Mumbai Indians,Kings XI Punjab,Mumbai Indians,bat,Kings XI Punjab,team 2,team 1
619,Royal Challengers Bangalore,Gujarat Lions,Gujarat Lions,field,Royal Challengers Bangalore,team 1,team 2
620,Rising Pune Supergiants,Kolkata Knight Riders,Rising Pune Supergiants,bat,Kolkata Knight Riders,team 2,team 1
621,Kings XI Punjab,Sunrisers Hyderabad,Kings XI Punjab,bat,Sunrisers Hyderabad,team 2,team 1
622,Mumbai Indians,Delhi Daredevils,Delhi Daredevils,field,Mumbai Indians,team 1,team 2
623,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Royal Challengers Bangalore,team 2,team 2
624,Delhi Daredevils,Rising Pune Supergiants,Rising Pune Supergiants,field,Rising Pune Supergiants,team 2,team 2
625,Royal Challengers Bangalore,Kings XI Punjab,Kings XI Punjab,field,Royal Challengers Bangalore,team 1,team 2
626,Kolkata Knight Riders,Gujarat Lions,Gujarat Lions,field,Gujarat Lions,team 2,team 2
627,Sunrisers Hyderabad,Delhi Daredevils,Delhi Daredevils,field,Delhi Daredevils,team 2,team 2
628,Kings XI Punjab,Rising Pune Supergiants,Kings XI Punjab,bat,Rising Pune Supergiants,team 2,team 1
629,Mumbai Indians,Gujarat Lions,Gujarat Lions,field,Gujarat Lions,team 2,team 2
630,Kolkata Knight Riders,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Kolkata Knight Riders,team 1,team 2
631,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Royal Challengers Bangalore,team 2,team 2
632,Gujarat Lions,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Royal Challengers Bangalore,team 2,team 2
633,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders,field,Sunrisers Hyderabad,team 1,team 2
634,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,team 2,team 2
635,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,Sunrisers Hyderabad,team 1,team 1

In [16]:
match = string_remover(match,include=['toss_decision','toss_win'],list1=b,list2 = a)

In [17]:
b

['toss_decision', 'field', 'bat', 'toss_win', 'team 1', 'team 2']

In [18]:
match

,team1,team2,toss_winner,toss_decision,winner,win,toss_win
0,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,1,Sunrisers Hyderabad,team 1,1
1,Mumbai Indians,Rising Pune Supergiants,Rising Pune Supergiants,1,Rising Pune Supergiants,team 2,1
2,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,1,Kolkata Knight Riders,team 2,1
3,Rising Pune Supergiants,Kings XI Punjab,Kings XI Punjab,1,Kings XI Punjab,team 2,1
4,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,2,Royal Challengers Bangalore,team 1,2
5,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,1,Sunrisers Hyderabad,team 2,1
6,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,1,Mumbai Indians,team 2,1
7,Royal Challengers Bangalore,Kings XI Punjab,Royal Challengers Bangalore,2,Kings XI Punjab,team 2,2
8,Delhi Daredevils,Rising Pune Supergiants,Rising Pune Supergiants,1,Delhi Daredevils,team 1,1
9,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,1,Mumbai Indians,team 2,1
10,Kings XI Punjab,Kolkata Knight Riders,Kolkata Knight Riders,1,Kolkata Knight Riders,team 2,1
11,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,1,Mumbai Indians,team 2,1
12,Rising Pune Supergiants,Gujarat Lions,Gujarat Lions,1,Gujarat Lions,team 2,1
13,Kolkata Knight Riders,Sunrisers Hyderabad,Sunrisers Hyderabad,1,Kolkata Knight Riders,team 1,1
14,Delhi Daredevils,Kings XI Punjab,Delhi Daredevils,2,Delhi Daredevils,team 1,2
15,Gujarat Lions,Mumbai Indians,Mumbai Indians,1,Mumbai Indians,team 2,1
16,Rising Pune Supergiants,Royal Challengers Bangalore,Royal Challengers Bangalore,1,Rising Pune Supergiants,team 1,1
17,Delhi Daredevils,Kolkata Knight Riders,Delhi Daredevils,2,Kolkata Knight Riders,team 2,2
18,Sunrisers Hyderabad,Kings XI Punjab,Kings XI Punjab,1,Sunrisers Hyderabad,team 1,1
19,Royal Challengers Bangalore,Gujarat Lions,Gujarat Lions,1,Royal Challengers Bangalore,team 1,1
20,Sunrisers Hyderabad,Delhi Daredevils,Sunrisers Hyderabad,2,Sunrisers Hyderabad,team 1,2
21,Kings XI Punjab,Mumbai Indians,Mumbai Indians,1,Mumbai Indians,team 2,1
22,Kolkata Knight Riders,Gujarat Lions,Gujarat Lions,1,Gujarat Lions,team 2,1
23,Mumbai Indians,Delhi Daredevils,Delhi Daredevils,1,Mumbai Indians,team 1,1
24,Sunrisers Hyderabad,Rising Pune Supergiants,Rising Pune Supergiants,1,Rising Pune Supergiants,team 2,1
25,Kings XI Punjab,Gujarat Lions,Gujarat Lions,1,Kings XI Punjab,team 1,1
26,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,1,Kolkata Knight Riders,team 1,1
27,Rising Pune Supergiants,Mumbai Indians,Mumbai Indians,1,Rising Pune Supergiants,team 1,1
28,Rising Pune Supergiants,Kolkata Knight Riders,Kolkata Knight Riders,1,Kolkata Knight Riders,team 2,1
29,Royal Challengers Bangalore,Gujarat Lions,Gujarat Lions,1,Gujarat Lions,team 2,1
...,...,...,...,...,...,...,...
606,Gujarat Lions,Delhi Daredevils,Delhi Daredevils,1,Delhi Daredevils,team 2,1
607,Kolkata Knight Riders,Kings XI Punjab,Kings XI Punjab,1,Kolkata Knight Riders,team 1,1
608,Delhi Daredevils,Rising Pune Supergiants,Rising Pune Supergiants,1,Rising Pune Supergiants,team 2,1
609,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,1,Sunrisers Hyderabad,team 2,1
610,Rising Pune Supergiants,Royal Challengers Bangalore,Royal Challengers Bangalore,1,Royal Challengers Bangalore,team 2,1
611,Kings XI Punjab,Delhi Daredevils,Delhi Daredevils,1,Kings XI Punjab,team 1,1
612,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,1,Sunrisers Hyderabad,team 1,1
613,Kolkata Knight Riders,Gujarat Lions,Gujarat Lions,1,Gujarat Lions,team 2,1
614,Royal Challengers Bangalore,Kings XI Punjab,Kings XI Punjab,1,Royal Challengers Bangalore,team 1,1
615,Sunrisers Hyderabad,Rising Pune Supergiants,Sunrisers Hyderabad,2,Sunrisers Hyderabad,team 1,2
616,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,1,Mumbai Indians,team 2,1
617,Sunrisers Hyderabad,Delhi Daredevils,Delhi Daredevils,1,Delhi Daredevils,team 2,1
618,Mumbai Indians,Kings XI Punjab,Mumbai Indians,2,Kings XI Punjab,team 2,2
619,Royal Challengers Bangalore,Gujarat Lions,Gujarat Lions,1,Royal Challengers Bangalore,team 1,1
620,Rising Pune Supergiants,Kolkata Knight Riders,Rising Pune Supergiants,2,Kolkata Knight Riders,team 2,2
621,Kings XI Punjab,Sunrisers Hyderabad,Kings XI Punjab,2,Sunrisers Hyderabad,team 2,2
622,Mumbai Indians,Delhi Daredevils,Delhi Daredevils,1,Mumbai Indians,team 1,1
623,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,1,Royal Challengers Bangalore,team 2,1
624,Delhi Daredevils,Rising Pune Supergiants,Rising Pune Supergiants,1,Rising Pune Supergiants,team 2,1
625,Royal Challengers Bangalore,Kings XI Punjab,Kings XI Punjab,1,Royal Challengers Bangalore,team 1,1
626,Kolkata Knight Riders,Gujarat Lions,Gujarat Lions,1,Gujarat Lions,team 2,1
627,Sunrisers Hyderabad,Delhi Daredevils,Delhi Daredevils,1,Delhi Daredevils,team 2,1
628,Kings XI Punjab,Rising Pune Supergiants,Kings XI Punjab,2,Rising Pune Supergiants,team 2,2
629,Mumbai Indians,Gujarat Lions,Gujarat Lions,1,Gujarat Lions,team 2,1
630,Kolkata Knight Riders,Sunrisers Hyderabad,Sunrisers Hyderabad,1,Kolkata Knight Riders,team 1,1
631,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,1,Royal Challengers Bangalore,team 2,1
632,Gujarat Lions,Royal Challengers Bangalore,Royal Challengers Bangalore,1,Royal Challengers Bangalore,team 2,1
633,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders,1,Sunrisers Hyderabad,team 1,1
634,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,1,Sunrisers Hyderabad,team 2,1
635,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,2,Sunrisers Hyderabad,team 1,2

In [19]:
points.drop('Tied',inplace=True,axis=1)

In [20]:
points.index = ['Chennai Super Kings', 'Deccan Chargers', 'Delhi Capitals',
       'Gujarat Lions', 'Kings XI Punjab', 'Kochi Tuskers Kerala',
       'Kolkata Knight Riders', 'Mumbai Indians',
       'Pune Warriors India', 'Rajasthan Royals',
       'Rising Pune Supergiants', 'Royal Challengers Bangalore',
       'Sunrisers Hyderabad']

In [21]:
points.index.name = 'Team'

In [22]:
for i in [match[match['team2']=='Delhi Daredevils'].index,match[match['team2']=='Pune Warriors'].index]:
    for i in i:
        match.drop(i,inplace=True)

In [23]:
for i in [match[match['team1']=='Delhi Daredevils'].index,match[match['team1']=='Pune Warriors'].index]:
    for i in i:
        match.drop(i,inplace=True)

In [24]:
points.to_csv('IPL_Points_Table.csv')

In [25]:
match['Team1_pts'] = None
match['Team1_RR'] = None
match['Team2_pts'] = None
match['Team2_RR'] = None
for i in match.index:
    match['Team1_pts'][i] = points.Pts[match.team1[i]]
    match['Team1_RR'][i] = points['Net RR'][match.team1[i]]
    match['Team2_pts'][i] = points.Pts[match.team2[i]]
    match['Team2_RR'][i] = points['Net RR'][match.team2[i]]
for i in match.index:
    match['Team2_pts'][i] = points.Pts[match.team2[i]]
    match['Team2_RR'][i] = points['Net RR'][match.team2[i]]

C:\Users\Lenovo\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\Lenovo\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys
C:\Users\Lenovo\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\Lenovo\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
C:\Users\Lenovo\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()
C:\Users\Lenovo\Anaconda3\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if sys.path[0] == '':

In [26]:
points

,Pld,Won,Lost,N/R,Net RR,Pts
Team,,,,,,
Chennai Super Kings,14.400000,8.700000,5.500000,0.200000,0.358400,17.600000
Deccan Chargers,14.400000,5.400000,8.800000,0.200000,-0.169600,11.000000
Delhi Capitals,14.333333,6.333333,7.750000,0.250000,-0.173417,12.916667
Gujarat Lions,14.000000,6.500000,7.500000,0.000000,-0.393000,13.000000
Kings XI Punjab,14.333333,6.750000,7.583333,0.000000,-0.197417,13.500000
Kochi Tuskers Kerala,14.000000,6.000000,8.000000,0.000000,-0.214000,12.000000
Kolkata Knight Riders,14.333333,7.166667,6.833333,0.333333,0.083167,14.666667
Mumbai Indians,14.333333,8.250000,6.000000,0.083333,0.313333,16.583333
Pune Warriors India,15.333333,4.000000,11.000000,0.333333,-0.563667,8.333333
Rajasthan Royals,14.400000,7.200000,6.700000,0.500000,-0.097900,14.900000
Rising Pune Supergiants,14.000000,7.000000,7.000000,0.000000,0.095500,14.000000
Royal Challengers Bangalore,14.333333,6.583333,7.250000,0.500000,-0.050583,13.666667
Sunrisers Hyderabad,14.285714,7.714286,6.428571,0.142857,0.152857,15.571429

In [27]:
RC = RandomForestClassifier(random_state=815)

In [28]:
match.win = match['win']

In [29]:
match[['Team1_pts','Team1_RR','Team2_pts','Team2_RR',]]

    Team1_pts   Team1_RR Team2_pts   Team2_RR
0     15.5714   0.152857   13.6667 -0.0505833
1     16.5833   0.313333        14     0.0955
2          13     -0.393   14.6667  0.0831667
3          14     0.0955      13.5  -0.197417
5          13     -0.393   15.5714   0.152857
6     14.6667  0.0831667   16.5833   0.313333
7     13.6667 -0.0505833      13.5  -0.197417
9     15.5714   0.152857   16.5833   0.313333
10       13.5  -0.197417   14.6667  0.0831667
11    13.6667 -0.0505833   16.5833   0.313333
12         14     0.0955        13     -0.393
13    14.6667  0.0831667   15.5714   0.152857
15         13     -0.393   16.5833   0.313333
16         14     0.0955   13.6667 -0.0505833
18    15.5714   0.152857      13.5  -0.197417
19    13.6667 -0.0505833        13     -0.393
21       13.5  -0.197417   16.5833   0.313333
22    14.6667  0.0831667        13     -0.393
24    15.5714   0.152857        14     0.0955
25       13.5  -0.197417        13     -0.393
26    14.6667  0.0831667   13.6667 -0.0505833
27         14     0.0955   16.5833   0.313333
28         14     0.0955   14.6667  0.0831667
29    13.6667 -0.0505833        13     -0.393
31    15.5714   0.152857      13.5  -0.197417
32         14     0.0955   13.6667 -0.0505833
33         13     -0.393   16.5833   0.313333
35    15.5714   0.152857   14.6667  0.0831667
36    13.6667 -0.0505833   16.5833   0.313333
37         13     -0.393        14     0.0955
..        ...        ...       ...        ...
596   16.5833   0.313333      13.5  -0.197417
597   15.5714   0.152857        14     0.0955
599   14.6667  0.0831667   16.5833   0.313333
600        14     0.0955        13     -0.393
602   15.5714   0.152857   13.6667 -0.0505833
603      13.5  -0.197417        13     -0.393
604        14     0.0955   16.5833   0.313333
605   13.6667 -0.0505833   14.6667  0.0831667
607   14.6667  0.0831667      13.5  -0.197417
609        13     -0.393   15.5714   0.152857
610        14     0.0955   13.6667 -0.0505833
612   15.5714   0.152857   16.5833   0.313333
613   14.6667  0.0831667        13     -0.393
614   13.6667 -0.0505833      13.5  -0.197417
615   15.5714   0.152857        14     0.0955
616   13.6667 -0.0505833   16.5833   0.313333
618   16.5833   0.313333      13.5  -0.197417
619   13.6667 -0.0505833        13     -0.393
620        14     0.0955   14.6667  0.0831667
621      13.5  -0.197417   15.5714   0.152857
623   14.6667  0.0831667   13.6667 -0.0505833
625   13.6667 -0.0505833      13.5  -0.197417
626   14.6667  0.0831667        13     -0.393
628      13.5  -0.197417        14     0.0955
629   16.5833   0.313333        13     -0.393
630   14.6667  0.0831667   15.5714   0.152857
632        13     -0.393   13.6667 -0.0505833
633   15.5714   0.152857   14.6667  0.0831667
634        13     -0.393   15.5714   0.152857
635   15.5714   0.152857   13.6667 -0.0505833

[449 rows x 4 columns]

In [30]:
RC.fit(X=match[['Team1_pts','Team1_RR','Team2_pts','Team2_RR','toss_decision','toss_win']],y=match.win)

C:\Users\Lenovo\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=815,
                       verbose=0, warm_start=False)

In [31]:
def Predicter(team1,team2,toss_winner,toss_decision):
    Team1_pts = points.Pts[team1]
    Team1_RR = points['Net RR'][team1]
    Team2_pts = points.Pts[team2]
    Team2_RR = points['Net RR'][team2]
    pred = RC.predict([[Team1_pts,Team1_RR,Team2_pts,Team2_RR,toss_decision,toss_winner]])
    if pred == 'team 1':
        return team1
    else:
        return team2

In [33]:
Predicter('Chennai Super Kings','Rajasthan Royals',toss_decision=1,toss_winner=2)

'Chennai Super Kings'